#pylint: skip-file
"""create table produk

Revision ID: 31398f6c3b60
Revises: 
Create Date: 2023-08-20 20:31:13.724552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31398f6c3b60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barang',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('produk', sa.String(), nullable=True),
    sa.Column('satuan', sa.String(), nullable=True),
    sa.Column('jumlah', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang')
    # ### end Alembic commands ###
